services:
  postgres_db:
    env_file: core/.env
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /home/lucianopinto/DevApps/postgres_db:/var/lib/postgresql/data

  pgadmin:
    env_file: core/.env
    image: dpage/pgadmin4
    container_name: PgAdminCont
    depends_on:
      - postgres_db
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

volumes:
  postgres_db:
    driver: local

