# Generated by Django 4.2.7 on 2023-11-28 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_func', '0003_alter_funcionario_data_contratacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cad_func.setor'),
        ),
    ]
