# Generated by Django 4.2.7 on 2023-11-28 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_func', '0004_alter_funcionario_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='setor', to='cad_func.setor'),
        ),
    ]
